// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RestaurantAPI.Data;

#nullable disable

namespace RestaurantAPI.Migrations
{
    [DbContext(typeof(RestaurantContext))]
    partial class RestaurantContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IngredientPlat", b =>
                {
                    b.Property<int>("IngredientsId")
                        .HasColumnType("integer");

                    b.Property<int>("PlatsId")
                        .HasColumnType("integer");

                    b.HasKey("IngredientsId", "PlatsId");

                    b.HasIndex("PlatsId");

                    b.ToTable("PlatIngredients", (string)null);
                });

            modelBuilder.Entity("RestaurantAPI.Models.Commande", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClientId")
                        .HasColumnType("integer");

                    b.Property<int?>("CuisinierId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateHeure")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ServeurId")
                        .HasColumnType("integer");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("TableId")
                        .HasColumnType("integer");

                    b.Property<double>("Total")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("CuisinierId");

                    b.HasIndex("ServeurId");

                    b.HasIndex("TableId");

                    b.ToTable("Commandes");
                });

            modelBuilder.Entity("RestaurantAPI.Models.Facture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CommandeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModePaiement")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<double>("MontantTotal")
                        .HasColumnType("double precision");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("CommandeId")
                        .IsUnique();

                    b.ToTable("Factures");
                });

            modelBuilder.Entity("RestaurantAPI.Models.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SeuilAlerte")
                        .HasColumnType("integer");

                    b.Property<string>("Unite")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("RestaurantAPI.Models.LigneCommande", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CommandeId")
                        .HasColumnType("integer");

                    b.Property<int>("PlatId")
                        .HasColumnType("integer");

                    b.Property<double>("PrixUnitaire")
                        .HasColumnType("double precision");

                    b.Property<int>("Quantite")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CommandeId");

                    b.HasIndex("PlatId");

                    b.ToTable("LigneCommandes");
                });

            modelBuilder.Entity("RestaurantAPI.Models.Personne", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Telephone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TypePersonne")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.HasKey("Id");

                    b.ToTable("Personnes");

                    b.HasDiscriminator<string>("TypePersonne").HasValue("Personne");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("RestaurantAPI.Models.Planning", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EmployeId")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("HeureDebut")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("HeureFin")
                        .HasColumnType("interval");

                    b.HasKey("Id");

                    b.HasIndex("EmployeId");

                    b.ToTable("Plannings");
                });

            modelBuilder.Entity("RestaurantAPI.Models.Plat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Categorie")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("Disponible")
                        .HasColumnType("boolean");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double>("Prix")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Plats");
                });

            modelBuilder.Entity("RestaurantAPI.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan>("Heure")
                        .HasColumnType("interval");

                    b.Property<int>("NbPersonnes")
                        .HasColumnType("integer");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("TableId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("TableId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("RestaurantAPI.Models.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateMAJ")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IngredientId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantite")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId")
                        .IsUnique();

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("RestaurantAPI.Models.Table", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacite")
                        .HasColumnType("integer");

                    b.Property<int>("Numero")
                        .HasColumnType("integer");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Numero")
                        .IsUnique();

                    b.ToTable("Tables");
                });

            modelBuilder.Entity("RestaurantAPI.Models.Utilisateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("PersonneId")
                        .HasColumnType("integer");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PersonneId");

                    b.ToTable("Utilisateurs");
                });

            modelBuilder.Entity("RestaurantAPI.Models.Client", b =>
                {
                    b.HasBaseType("RestaurantAPI.Models.Personne");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("Client");
                });

            modelBuilder.Entity("RestaurantAPI.Models.Employe", b =>
                {
                    b.HasBaseType("RestaurantAPI.Models.Personne");

                    b.Property<DateTime>("DateEmbauche")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Poste")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<double>("Salaire")
                        .HasColumnType("double precision");

                    b.HasDiscriminator().HasValue("Employe");
                });

            modelBuilder.Entity("RestaurantAPI.Models.Cuisinier", b =>
                {
                    b.HasBaseType("RestaurantAPI.Models.Employe");

                    b.Property<string>("Specialite")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasDiscriminator().HasValue("Cuisinier");
                });

            modelBuilder.Entity("RestaurantAPI.Models.Manager", b =>
                {
                    b.HasBaseType("RestaurantAPI.Models.Employe");

                    b.HasDiscriminator().HasValue("Manager");
                });

            modelBuilder.Entity("RestaurantAPI.Models.Serveur", b =>
                {
                    b.HasBaseType("RestaurantAPI.Models.Employe");

                    b.Property<string>("Zone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasDiscriminator().HasValue("Serveur");
                });

            modelBuilder.Entity("IngredientPlat", b =>
                {
                    b.HasOne("RestaurantAPI.Models.Ingredient", null)
                        .WithMany()
                        .HasForeignKey("IngredientsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RestaurantAPI.Models.Plat", null)
                        .WithMany()
                        .HasForeignKey("PlatsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RestaurantAPI.Models.Commande", b =>
                {
                    b.HasOne("RestaurantAPI.Models.Client", "Client")
                        .WithMany("Commandes")
                        .HasForeignKey("ClientId");

                    b.HasOne("RestaurantAPI.Models.Cuisinier", "Cuisinier")
                        .WithMany("CommandesPreparees")
                        .HasForeignKey("CuisinierId");

                    b.HasOne("RestaurantAPI.Models.Serveur", "Serveur")
                        .WithMany("Commandes")
                        .HasForeignKey("ServeurId");

                    b.HasOne("RestaurantAPI.Models.Table", "Table")
                        .WithMany("Commandes")
                        .HasForeignKey("TableId");

                    b.Navigation("Client");

                    b.Navigation("Cuisinier");

                    b.Navigation("Serveur");

                    b.Navigation("Table");
                });

            modelBuilder.Entity("RestaurantAPI.Models.Facture", b =>
                {
                    b.HasOne("RestaurantAPI.Models.Commande", "Commande")
                        .WithOne("Facture")
                        .HasForeignKey("RestaurantAPI.Models.Facture", "CommandeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Commande");
                });

            modelBuilder.Entity("RestaurantAPI.Models.LigneCommande", b =>
                {
                    b.HasOne("RestaurantAPI.Models.Commande", "Commande")
                        .WithMany("LigneCommandes")
                        .HasForeignKey("CommandeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RestaurantAPI.Models.Plat", "Plat")
                        .WithMany("LigneCommandes")
                        .HasForeignKey("PlatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Commande");

                    b.Navigation("Plat");
                });

            modelBuilder.Entity("RestaurantAPI.Models.Planning", b =>
                {
                    b.HasOne("RestaurantAPI.Models.Employe", "Employe")
                        .WithMany("Plannings")
                        .HasForeignKey("EmployeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employe");
                });

            modelBuilder.Entity("RestaurantAPI.Models.Reservation", b =>
                {
                    b.HasOne("RestaurantAPI.Models.Client", "Client")
                        .WithMany("Reservations")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RestaurantAPI.Models.Table", "Table")
                        .WithMany("Reservations")
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Table");
                });

            modelBuilder.Entity("RestaurantAPI.Models.Stock", b =>
                {
                    b.HasOne("RestaurantAPI.Models.Ingredient", "Ingredient")
                        .WithOne("Stock")
                        .HasForeignKey("RestaurantAPI.Models.Stock", "IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("RestaurantAPI.Models.Utilisateur", b =>
                {
                    b.HasOne("RestaurantAPI.Models.Personne", "Personne")
                        .WithMany()
                        .HasForeignKey("PersonneId");

                    b.Navigation("Personne");
                });

            modelBuilder.Entity("RestaurantAPI.Models.Commande", b =>
                {
                    b.Navigation("Facture");

                    b.Navigation("LigneCommandes");
                });

            modelBuilder.Entity("RestaurantAPI.Models.Ingredient", b =>
                {
                    b.Navigation("Stock");
                });

            modelBuilder.Entity("RestaurantAPI.Models.Plat", b =>
                {
                    b.Navigation("LigneCommandes");
                });

            modelBuilder.Entity("RestaurantAPI.Models.Table", b =>
                {
                    b.Navigation("Commandes");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("RestaurantAPI.Models.Client", b =>
                {
                    b.Navigation("Commandes");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("RestaurantAPI.Models.Employe", b =>
                {
                    b.Navigation("Plannings");
                });

            modelBuilder.Entity("RestaurantAPI.Models.Cuisinier", b =>
                {
                    b.Navigation("CommandesPreparees");
                });

            modelBuilder.Entity("RestaurantAPI.Models.Serveur", b =>
                {
                    b.Navigation("Commandes");
                });
#pragma warning restore 612, 618
        }
    }
}
